-- Create chat_temporal table
create table if not exists public.chat_temporal (
    id bigint generated by default as identity primary key,
    session_id text not null,
    message text not null,
    sender text not null, -- 'user' or 'bot'
    created_at timestamp with time zone default now() not null,
    update_at timestamp with time zone default now() not null
);

-- Create n8n_chat_temporal_ai table
create table if not exists public.n8n_chat_temporal_ai (
    id bigint generated by default as identity primary key,
    session_id text not null,
    message text not null,
    created_at timestamp with time zone default now() not null
);

-- Enable RLS (Security Best Practice)
alter table public.chat_temporal enable row level security;
alter table public.n8n_chat_temporal_ai enable row level security;

-- Policies (Open for now as per likely requirement for n8n/guest access, but ideally restricted)
create policy "Enable all access for now" on public.chat_temporal for all using (true);
create policy "Enable all access for now" on public.n8n_chat_temporal_ai for all using (true);

-- Ensure permissions are granted to API roles
GRANT ALL ON TABLE public.chat_temporal TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.n8n_chat_temporal_ai TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.chat_temporal_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.n8n_chat_temporal_ai_id_seq TO anon, authenticated, service_role;

-- Seed Data
INSERT INTO public.chat_temporal (id, session_id, message, update_at, created_at, sender)
VALUES
(1, 'sess_001', 'Hola, tengo una incidencia con una fuga de agua', NOW(), NOW() - INTERVAL '5 minutes', 'user'),
(2, 'sess_001', 'Gracias por avisar, ¿podrías indicarme la ubicación exacta?', NOW(), NOW() - INTERVAL '4 minutes', 'bot'),
(3, 'sess_001', 'En el garaje, cerca de la plaza 14', NOW(), NOW() - INTERVAL '3 minutes', 'user');

-- Restart identity to avoid collision after manual insert with explicit IDs
SELECT setval(pg_get_serial_sequence('public.chat_temporal', 'id'), 4, false);

INSERT INTO public.n8n_chat_temporal_ai (id, session_id, message)
VALUES
(1, 'sess_001', 'Incidencia detectada: fuga de agua en garaje. Prioridad alta. Sentimiento negativo.'),
(2, 'sess_002', 'Incidencia de electricidad con urgencia media. Usuario neutral.');

-- Restart identity
SELECT setval(pg_get_serial_sequence('public.n8n_chat_temporal_ai', 'id'), 3, false);
